spring.application.name=ecommerce
# 1. Veritabanı Bağlantı Ayarları (JDBC URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce_db
spring.datasource.username=maksatbekzhakypov
spring.datasource.password=

# 2. Hibernate / JPA Sihirbazlık Ayarları
# update: Java'da yazdığın sınıflara göre PostgreSQL'de tabloları otomatik oluşturur/günceller
spring.jpa.hibernate.ddl-auto=update

# Konsolda arkada dönen SQL sorgularını temiz bir şekilde görmemizi sağlar
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Yüklenebilecek maksimum dosya boyutu (Örn: 10MB yaptık)
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB